In [1]:
import pandas as pd
import numpy as np

위의 코드는 마르코프 체인의 한 예시를 시뮬레이션하는 것입니다. 마르코프 체인은 미래의 상태가 오직 현재 상태에만 의존하는 확률 과정을 모델링하는 데 사용됩니다. 이러한 특성 때문에, 마르코프 체인은 다양한 분야에서 예측 모델링에 활용됩니다.

코드에서 T는 전이 행렬(transition matrix)로, 한 상태에서 다른 상태로의 전환 확률을 나타냅니다. 각 열의 합은 1이 되어야 합니다, 이는 어떤 상태에서 출발할 때 다른 상태들로 전환될 확률의 합이 1이라는 것을 의미합니다. p는 초기 상태 분포를 나타내는 벡터입니다.

k는 시간의 경과를 나타내며, 이 코드는 T를 여러 번 k에 대해 거듭제곱하여 어떻게 상태 분포가 변화하는지를 보여줍니다. np.linalg.matrix_power(T, i)는 T를 i번 거듭제곱하여 시간 i에서의 전이 행렬을 계산하고, .dot(p)는 이 전이 행렬을 초기 분포 p에 적용하여 시간 i에서의 상태 분포를 계산합니다.

이 코드를 통해 배울 수 있는 주요 개념은 다음과 같습니다:

시간에 따른 상태 분포의 변화: T^k를 계산함으로써, 우리는 시간이 지남에 따라 시스템의 상태가 어떻게 변화하는지 볼 수 있습니다. 이는 동적 시스템을 이해하는 데 중요한 개념입니다.

정상 상태(Steady State) 도달: 마르코프 체인은 종종 시간이 충분히 지난 후에 정상 상태 또는 평형 상태에 도달합니다. 이 상태에서는 상태 분포가 더 이상 시간에 따라 변하지 않습니다. 코드에서 k가 증가함에 따라, 계산된 상태 분포가 어떻게 변화하는지 관찰함으로써 정상 상태에 도달하는지 여부를 확인할 수 있습니다.

장기적 예측: 마르코프 체인의 정상 상태는 시스템이 장기적으로 어떤 상태에 머물 확률이 높은지를 예측할 수 있게 해줍니다. 이는 재무, 생태학, 컴퓨터 과학 등 다양한 분야에서 의사결정에 중요한 정보를 제공할 수 있습니다.

실제로 코드를 실행하여 k 값이 다양할 때의 결과를 관찰하면, 마르코프 체인이 시간이 지남에 따라 어떻게 진화하는지, 그리고 특정 조건 하에서는 시스템이 어떤 평형 상태에 도달하는지를 직접 볼 수 있습니다.

이 결과는 마르코프 체인이 결국 정상 상태(Steady State) 또는 평형 상태(Equilibrium State)에 도달한다는 중요한 개념을 보여줍니다. 여기서 정상 상태란, 시간이 지남에 따라 시스템의 상태 분포가 더 이상 변하지 않는 상태를 의미합니다. 즉, 전이 행렬 
�
T를 반복적으로 적용하더라도, 상태 분포가 일정한 값으로 수렴하게 됩니다.

여기서 주목할 점은, 초기에 벡터 
�
p에 전이 행렬 
�
T를 한 번 적용했을 때의 결과([0.65, 0.35])와, 
�
T를 반복적으로 적용한 결과가 결국 [0.63636364, 0.36363636]으로 수렴한다는 것입니다. 이는 다음과 같은 의미를 가집니다:

장기적 안정성: 마르코프 체인은 시간이 지나면서 특정한 안정된 상태 분포로 수렴하는 경향이 있습니다. 이는 시스템이 어떤 초기 상태에서 시작하든지 간에, 장기적으로는 특정한 패턴 또는 분포로 안정화될 것임을 의미합니다.

예측 가능성: 이러한 성질은 시스템의 장기적인 행동을 예측할 수 있게 해줍니다. 특히, 경제학, 생태학, 컴퓨터 네트워크 분석 등에서 중요한 의사결정을 내릴 때 이러한 장기적 안정성을 기반으로 할 수 있습니다.

초기 상태의 영향 감소: 시간이 지남에 따라 시스템의 초기 상태가 최종 상태 분포에 미치는 영향이 줄어듭니다. 즉, 장기적으로는 초기 조건보다는 시스템의 동적 특성(여기서는 전이 행렬 
�
T)이 더 중요해집니다.

결과적으로, 마르코프 체인을 이용한 이러한 분석은 다양한 시스템이 시간에 따라 어떻게 진화하는지 이해하는 데 매우 유용합니다. 특히, 정상 상태에 도달했을 때의 상태 분포를 알면, 시스템이 장기적으로 어떤 상태에 가장 많이 머물 것인지를 예측할 수 있습니다. 이는 경제, 공학, 생태학, 사회 과학 등 다양한 분야에서 중요한 의미를 가지며, 복잡한 시스템의 동적 거동을 분석하고 예측하는 데 있어 핵심적인 도구가 됩니다.

In [16]:
T = np.array([
    [0.6,0.7],[0.4,0.3]
])
p = np.array(
    [0.5,0.5]
)
k = [1,2,10,100,100000]
for i in k:
    Tk = np.linalg.matrix_power(T,i)
    print(Tk.dot(p))



[0.65 0.35]
[0.635 0.365]
[0.63636364 0.36363636]
[0.63636364 0.36363636]
[0.63636364 0.36363636]


In [4]:
A = np.array([
    [1,1,0,1,1,0,0,0,0],
    [0,1,1,0,1,1,0,0,0],
    [0,0,0,1,1,0,1,1,0],
    [0,0,0,0,1,1,0,1,1]
])

B = np.array([19,18,28,25])
# 최소 제곱 해 구하기
X_lstsq, residuals, rank, s = np.linalg.lstsq(A, B, rcond=None)

X_lstsq


array([ 1.        ,  2.33333333,  1.33333333,  5.66666667, 10.        ,
        4.33333333,  4.66666667,  7.66666667,  3.        ])

In [5]:
import numpy as np

# 주어진 행렬 A와 B 벡터
A = np.array([
    [1, 1, 0, 1, 1, 0, 0, 0, 0],
    [0, 1, 1, 0, 1, 1, 0, 0, 0],
    [0, 0, 0, 1, 1, 0, 1, 1, 0],
    [0, 0, 0, 0, 1, 1, 0, 1, 1]
])

B = np.array([19, 18, 28, 25])

# 선형 최소제곱 문제의 해를 구함
x, residuals, rank, s = np.linalg.lstsq(A, B, rcond=None)

# 해 출력
print("Solution:", x)


Solution: [ 1.          2.33333333  1.33333333  5.66666667 10.          4.33333333
  4.66666667  7.66666667  3.        ]


In [10]:
residuals

array([], dtype=float64)

In [13]:
a = np.array([
    [1,2,3],[2,1,2],[3,2,4]
])
np.linalg.inv(a)



array([[ 1.48029737e-16,  2.00000000e+00, -1.00000000e+00],
       [ 2.00000000e+00,  5.00000000e+00, -4.00000000e+00],
       [-1.00000000e+00, -4.00000000e+00,  3.00000000e+00]])

In [15]:
import numpy as np

# 주어진 행렬을 NumPy 배열로 나타냄
A = np.array([[1,2,3],[2,1,2],[3,2,4]])

# 역행렬 계산
A_inv = np.linalg.inv(A)

print(A_inv)

[[ 1.48029737e-16  2.00000000e+00 -1.00000000e+00]
 [ 2.00000000e+00  5.00000000e+00 -4.00000000e+00]
 [-1.00000000e+00 -4.00000000e+00  3.00000000e+00]]
